# Generated by Django 3.2.4 on 2021-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Gold', 'gold'), ('USD/INR', 'usd/inr'), ('CrudeOil', 'crudeoil'), ('DOW', 'dow'), ('NASDAQ', 'nasdaq'), ('CAC', 'cac'), ('DAX', 'dax'), ('NIFTY', 'nifty')], max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('open', models.FloatField(blank=True)),
                ('high', models.FloatField(blank=True)),
                ('low', models.FloatField(blank=True)),
                ('close', models.FloatField(blank=True)),
                ('adjclose', models.FloatField(blank=True)),
                ('volume', models.PositiveIntegerField(blank=True)),
            ],
        ),
    ]
