# Generated by Django 3.2.4 on 2021-06-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_stockdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='username',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
