# Generated by Django 3.2.4 on 2021-06-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_stockdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='username',
        ),
    ]
